import type { Task, TaskStatus, TaskPriority } from './types'

export const TASK_STATUSES: TaskStatus[] = ['todo', 'in-progress', 'review', 'done', 'blocked']

export const TASK_PRIORITIES: TaskPriority[] = ['low', 'medium', 'high', 'critical']

export const PAGE_SIZE = 8

// Projects used in task relationships - mirrors key entries from features/projects/constants.ts
export const TASK_PROJECTS = [
  { id: 'p01', name: 'ProjectFlow Admin Dashboard' },
  { id: 'p02', name: 'E-Commerce Redesign' },
  { id: 'p03', name: 'AI-Powered Analytics Engine' },
  { id: 'p04', name: 'Mobile Banking App' },
  { id: 'p06', name: 'Cloud Migration' },
  { id: 'p09', name: 'Cybersecurity Audit Platform' },
  { id: 'p10', name: 'Learning Management System' },
  { id: 'p15', name: 'Healthcare Patient Portal' },
]

// Team members used in task relationships - mirrors key entries from features/users/constants.ts
export const TASK_ASSIGNEES = [
  { id: 'u01', name: 'Ada Lovelace' },
  { id: 'u02', name: 'Grace Hopper' },
  { id: 'u03', name: 'Alan Turing' },
  { id: 'u04', name: 'Katherine Johnson' },
  { id: 'u06', name: 'Margaret Hamilton' },
  { id: 'u07', name: 'Tim Berners-Lee' },
  { id: 'u09', name: 'Barbara Liskov' },
  { id: 'u10', name: 'Donald Knuth' },
  { id: 'u11', name: 'Sofia Kovalevskaya' },
  { id: 'u13', name: 'Hedy Lamarr' },
  { id: 'u15', name: 'Edsger Dijkstra' },
  { id: 'u16', name: 'Radia Perlman' },
  { id: 'u19', name: 'Ken Thompson' },
]

export const mockTasks: Task[] = [
  // ProjectFlow Admin Dashboard
  {
    id: 't01',
    name: 'Design sidebar navigation component',
    description: 'Create a responsive sidebar with collapsible sections, active state indicators, and smooth mobile drawer animation.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u11',
    assigneeName: 'Sofia Kovalevskaya',
    status: 'done',
    priority: 'high',
    progress: 100,
    dueDate: '2026-06-20',
    createdAt: '2026-05-10T09:00:00Z',
    tags: ['UI', 'React', 'Tailwind'],
  },
  {
    id: 't02',
    name: 'Implement authentication flow',
    description: 'Build login page with form validation, demo credentials card, and protected route guard using Zustand store.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u01',
    assigneeName: 'Ada Lovelace',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-06-15',
    createdAt: '2026-05-05T09:00:00Z',
    tags: ['Auth', 'Zustand'],
  },
  {
    id: 't03',
    name: 'Build analytics charts',
    description: 'Integrate Recharts library for revenue trends, user growth, task completion, and weekly activity charts.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u04',
    assigneeName: 'Katherine Johnson',
    status: 'done',
    priority: 'high',
    progress: 100,
    dueDate: '2026-07-01',
    createdAt: '2026-05-20T09:00:00Z',
    tags: ['Charts', 'Recharts'],
  },
  {
    id: 't04',
    name: 'Users management CRUD module',
    description: 'Implement full users page with search, filtering, sorting, pagination, and add/edit/delete/view dialogs.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u02',
    assigneeName: 'Grace Hopper',
    status: 'done',
    priority: 'high',
    progress: 100,
    dueDate: '2026-07-05',
    createdAt: '2026-06-01T09:00:00Z',
    tags: ['CRUD', 'React'],
  },
  {
    id: 't05',
    name: 'Projects management module',
    description: 'Build projects page with table, progress bars, team avatars, and full CRUD dialogs including budget and tag fields.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u06',
    assigneeName: 'Margaret Hamilton',
    status: 'done',
    priority: 'high',
    progress: 100,
    dueDate: '2026-07-08',
    createdAt: '2026-06-10T09:00:00Z',
    tags: ['CRUD', 'React'],
  },
  {
    id: 't06',
    name: 'Tasks management module',
    description: 'Build tasks page with relationships to projects and users, priority sorting, and full CRUD dialogs.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u01',
    assigneeName: 'Ada Lovelace',
    status: 'in-progress',
    priority: 'high',
    progress: 60,
    dueDate: '2026-07-15',
    createdAt: '2026-07-01T09:00:00Z',
    tags: ['CRUD', 'React'],
  },
  {
    id: 't07',
    name: 'Dark mode & theme system',
    description: 'Integrate CSS custom property-based theming with Zustand persistence and a theme toggle in the navbar.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u11',
    assigneeName: 'Sofia Kovalevskaya',
    status: 'in-progress',
    priority: 'medium',
    progress: 45,
    dueDate: '2026-07-20',
    createdAt: '2026-06-25T09:00:00Z',
    tags: ['Theme', 'CSS'],
  },
  {
    id: 't08',
    name: 'Responsive mobile layout audit',
    description: 'Review and fix all breakpoints across dashboard, analytics, users, projects, and tasks pages for mobile usability.',
    projectId: 'p01',
    projectName: 'ProjectFlow Admin Dashboard',
    assigneeId: 'u13',
    assigneeName: 'Hedy Lamarr',
    status: 'todo',
    priority: 'medium',
    progress: 0,
    dueDate: '2026-08-01',
    createdAt: '2026-07-01T09:00:00Z',
    tags: ['Mobile', 'QA'],
  },

  // E-Commerce Redesign
  {
    id: 't09',
    name: 'Homepage hero section redesign',
    description: 'Create a high-converting hero with animated product showcase, CTA buttons, and a trust signals bar.',
    projectId: 'p02',
    projectName: 'E-Commerce Redesign',
    assigneeId: 'u13',
    assigneeName: 'Hedy Lamarr',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-05-15',
    createdAt: '2026-03-20T09:00:00Z',
    tags: ['Design', 'Figma'],
  },
  {
    id: 't10',
    name: 'Checkout flow UX overhaul',
    description: 'Redesign 3-step checkout to a single-page flow with address autocomplete, payment summary, and order confirmation.',
    projectId: 'p02',
    projectName: 'E-Commerce Redesign',
    assigneeId: 'u11',
    assigneeName: 'Sofia Kovalevskaya',
    status: 'review',
    priority: 'critical',
    progress: 90,
    dueDate: '2026-07-05',
    createdAt: '2026-04-01T09:00:00Z',
    tags: ['UX', 'Checkout'],
  },
  {
    id: 't11',
    name: 'Product card component library',
    description: 'Build a design system card component with hover states, wishlist toggle, quick-add-to-cart, and rating stars.',
    projectId: 'p02',
    projectName: 'E-Commerce Redesign',
    assigneeId: 'u04',
    assigneeName: 'Katherine Johnson',
    status: 'review',
    priority: 'high',
    progress: 85,
    dueDate: '2026-07-08',
    createdAt: '2026-04-10T09:00:00Z',
    tags: ['Components', 'UI'],
  },
  {
    id: 't12',
    name: 'Mobile responsiveness testing',
    description: 'Cross-device QA on iOS Safari, Android Chrome, and tablet viewports for all redesigned pages.',
    projectId: 'p02',
    projectName: 'E-Commerce Redesign',
    assigneeId: 'u09',
    assigneeName: 'Barbara Liskov',
    status: 'todo',
    priority: 'high',
    progress: 0,
    dueDate: '2026-07-12',
    createdAt: '2026-06-15T09:00:00Z',
    tags: ['QA', 'Mobile'],
  },

  // AI-Powered Analytics Engine
  {
    id: 't13',
    name: 'Data ingestion pipeline',
    description: 'Build Kafka consumer service that normalizes raw event streams into structured analytics records in PostgreSQL.',
    projectId: 'p03',
    projectName: 'AI-Powered Analytics Engine',
    assigneeId: 'u10',
    assigneeName: 'Donald Knuth',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-06-01',
    createdAt: '2026-04-20T09:00:00Z',
    tags: ['Kafka', 'Python'],
  },
  {
    id: 't14',
    name: 'Predictive churn model training',
    description: 'Train and validate a gradient-boosted churn prediction model on 18 months of historical usage data.',
    projectId: 'p03',
    projectName: 'AI-Powered Analytics Engine',
    assigneeId: 'u09',
    assigneeName: 'Barbara Liskov',
    status: 'in-progress',
    priority: 'high',
    progress: 55,
    dueDate: '2026-08-01',
    createdAt: '2026-05-15T09:00:00Z',
    tags: ['ML', 'Python'],
  },
  {
    id: 't15',
    name: 'Real-time dashboard widgets',
    description: 'Build WebSocket-driven chart widgets that update live KPIs without page refresh.',
    projectId: 'p03',
    projectName: 'AI-Powered Analytics Engine',
    assigneeId: 'u04',
    assigneeName: 'Katherine Johnson',
    status: 'in-progress',
    priority: 'medium',
    progress: 30,
    dueDate: '2026-09-01',
    createdAt: '2026-06-01T09:00:00Z',
    tags: ['WebSocket', 'React'],
  },

  // Mobile Banking App
  {
    id: 't16',
    name: 'Biometric authentication module',
    description: 'Integrate FaceID/TouchID via react-native-biometrics with graceful PIN fallback and session token refresh.',
    projectId: 'p04',
    projectName: 'Mobile Banking App',
    assigneeId: 'u16',
    assigneeName: 'Radia Perlman',
    status: 'in-progress',
    priority: 'critical',
    progress: 35,
    dueDate: '2026-09-15',
    createdAt: '2026-06-20T09:00:00Z',
    tags: ['Security', 'React Native'],
  },
  {
    id: 't17',
    name: 'Fund transfer flow',
    description: 'Implement instant and scheduled fund transfers with beneficiary management and real-time balance updates.',
    projectId: 'p04',
    projectName: 'Mobile Banking App',
    assigneeId: 'u07',
    assigneeName: 'Tim Berners-Lee',
    status: 'todo',
    priority: 'critical',
    progress: 0,
    dueDate: '2026-10-01',
    createdAt: '2026-06-25T09:00:00Z',
    tags: ['Payments', 'API'],
  },
  {
    id: 't18',
    name: 'Push notification service',
    description: 'Set up Firebase Cloud Messaging for transaction alerts, login notifications, and promotional messages.',
    projectId: 'p04',
    projectName: 'Mobile Banking App',
    assigneeId: 'u19',
    assigneeName: 'Ken Thompson',
    status: 'todo',
    priority: 'high',
    progress: 0,
    dueDate: '2026-10-15',
    createdAt: '2026-07-01T09:00:00Z',
    tags: ['FCM', 'Node.js'],
  },

  // Cloud Migration
  {
    id: 't19',
    name: 'Database replication to RDS',
    description: 'Migrate 12 on-premise MySQL databases to AWS RDS with zero-downtime cutover using DMS.',
    projectId: 'p06',
    projectName: 'Cloud Migration',
    assigneeId: 'u15',
    assigneeName: 'Edsger Dijkstra',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-06-30',
    createdAt: '2026-05-12T09:00:00Z',
    tags: ['AWS', 'RDS', 'MySQL'],
  },
  {
    id: 't20',
    name: 'Terraform infrastructure modules',
    description: 'Write reusable Terraform modules for VPC, ECS clusters, ALB, and RDS with environment-specific variable overrides.',
    projectId: 'p06',
    projectName: 'Cloud Migration',
    assigneeId: 'u03',
    assigneeName: 'Alan Turing',
    status: 'in-progress',
    priority: 'high',
    progress: 70,
    dueDate: '2026-08-15',
    createdAt: '2026-05-20T09:00:00Z',
    tags: ['Terraform', 'IaC'],
  },
  {
    id: 't21',
    name: 'CI/CD pipeline setup',
    description: 'Configure GitHub Actions workflows for build, test, and deploy to staging/prod ECS with rollback triggers.',
    projectId: 'p06',
    projectName: 'Cloud Migration',
    assigneeId: 'u03',
    assigneeName: 'Alan Turing',
    status: 'review',
    priority: 'high',
    progress: 80,
    dueDate: '2026-08-20',
    createdAt: '2026-06-01T09:00:00Z',
    tags: ['CI/CD', 'GitHub Actions'],
  },

  // Cybersecurity Audit Platform
  {
    id: 't22',
    name: 'Vulnerability scanner integration',
    description: 'Integrate OpenVAS and Nessus APIs to schedule scans, parse results, and normalize findings into the audit DB.',
    projectId: 'p09',
    projectName: 'Cybersecurity Audit Platform',
    assigneeId: 'u16',
    assigneeName: 'Radia Perlman',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-06-10',
    createdAt: '2026-03-05T09:00:00Z',
    tags: ['Security', 'API'],
  },
  {
    id: 't23',
    name: 'Risk scoring algorithm',
    description: 'Implement CVSS-based risk scoring with custom weights for asset criticality and exploit availability.',
    projectId: 'p09',
    projectName: 'Cybersecurity Audit Platform',
    assigneeId: 'u15',
    assigneeName: 'Edsger Dijkstra',
    status: 'in-progress',
    priority: 'critical',
    progress: 65,
    dueDate: '2026-07-20',
    createdAt: '2026-04-15T09:00:00Z',
    tags: ['CVSS', 'Python'],
  },
  {
    id: 't24',
    name: 'PDF audit report generator',
    description: 'Build automated PDF report generation using WeasyPrint with executive summary, charts, and remediation steps.',
    projectId: 'p09',
    projectName: 'Cybersecurity Audit Platform',
    assigneeId: 'u09',
    assigneeName: 'Barbara Liskov',
    status: 'blocked',
    priority: 'high',
    progress: 20,
    dueDate: '2026-07-25',
    createdAt: '2026-05-01T09:00:00Z',
    tags: ['PDF', 'Reporting'],
  },

  // Learning Management System
  {
    id: 't25',
    name: 'Video streaming module',
    description: 'Implement HLS adaptive video streaming with playback speed, quality selection, and resume-from-timestamp.',
    projectId: 'p10',
    projectName: 'Learning Management System',
    assigneeId: 'u07',
    assigneeName: 'Tim Berners-Lee',
    status: 'done',
    priority: 'high',
    progress: 100,
    dueDate: '2026-05-20',
    createdAt: '2026-02-15T09:00:00Z',
    tags: ['Video', 'HLS'],
  },
  {
    id: 't26',
    name: 'Quiz and assessment engine',
    description: 'Build a flexible quiz system supporting MCQ, true/false, and short-answer with timed attempts and auto-grading.',
    projectId: 'p10',
    projectName: 'Learning Management System',
    assigneeId: 'u10',
    assigneeName: 'Donald Knuth',
    status: 'review',
    priority: 'high',
    progress: 88,
    dueDate: '2026-07-18',
    createdAt: '2026-04-20T09:00:00Z',
    tags: ['Quiz', 'React'],
  },
  {
    id: 't27',
    name: 'Certificate generation system',
    description: 'Auto-generate branded PDF certificates on course completion with QR code verification links.',
    projectId: 'p10',
    projectName: 'Learning Management System',
    assigneeId: 'u04',
    assigneeName: 'Katherine Johnson',
    status: 'todo',
    priority: 'medium',
    progress: 0,
    dueDate: '2026-07-25',
    createdAt: '2026-06-10T09:00:00Z',
    tags: ['PDF', 'QR'],
  },

  // Healthcare Patient Portal
  {
    id: 't28',
    name: 'Appointment booking calendar',
    description: 'Build a real-time appointment scheduling calendar with doctor availability, conflict detection, and reminders.',
    projectId: 'p15',
    projectName: 'Healthcare Patient Portal',
    assigneeId: 'u01',
    assigneeName: 'Ada Lovelace',
    status: 'done',
    priority: 'critical',
    progress: 100,
    dueDate: '2026-05-01',
    createdAt: '2026-01-15T09:00:00Z',
    tags: ['Calendar', 'React'],
  },
  {
    id: 't29',
    name: 'HIPAA-compliant audit logging',
    description: 'Implement immutable audit logs for all PHI access events with user, timestamp, action, and data fingerprinting.',
    projectId: 'p15',
    projectName: 'Healthcare Patient Portal',
    assigneeId: 'u19',
    assigneeName: 'Ken Thompson',
    status: 'review',
    priority: 'critical',
    progress: 80,
    dueDate: '2026-07-22',
    createdAt: '2026-03-01T09:00:00Z',
    tags: ['HIPAA', 'Security'],
  },
  {
    id: 't30',
    name: 'Telemedicine video call feature',
    description: 'Integrate WebRTC-based peer-to-peer video consultations with waiting room, screen share, and session recording.',
    projectId: 'p15',
    projectName: 'Healthcare Patient Portal',
    assigneeId: 'u07',
    assigneeName: 'Tim Berners-Lee',
    status: 'in-progress',
    priority: 'high',
    progress: 50,
    dueDate: '2026-07-28',
    createdAt: '2026-04-01T09:00:00Z',
    tags: ['WebRTC', 'Video'],
  },
]
