import type { Project, ProjectStatus, ProjectPriority } from './types'

export const STATUSES: ProjectStatus[] = ['planning', 'in-progress', 'review', 'completed', 'on-hold']

export const PRIORITIES: ProjectPriority[] = ['low', 'medium', 'high', 'critical']

export const PAGE_SIZE = 8

export const mockProjects: Project[] = [
  {
    id: 'p01',
    name: 'WorkNova Admin Dashboard',
    client: 'Internal',
    status: 'in-progress',
    priority: 'high',
    progress: 68,
    team: [
      { id: 'u01', name: 'Ada Lovelace' },
      { id: 'u02', name: 'Grace Hopper' },
      { id: 'u06', name: 'Margaret Hamilton' },
    ],
    dueDate: '2026-08-15',
    startDate: '2026-05-01',
    description: 'A comprehensive admin dashboard for managing projects, users, tasks, and analytics in real time.',
    budget: 48000,
    tags: ['React', 'TypeScript', 'Tailwind'],
  },
  {
    id: 'p02',
    name: 'E-Commerce Redesign',
    client: 'ShopNova Ltd.',
    status: 'review',
    priority: 'critical',
    progress: 91,
    team: [
      { id: 'u11', name: 'Sofia Kovalevskaya' },
      { id: 'u13', name: 'Hedy Lamarr' },
      { id: 'u21', name: 'Adele Goldberg' },
      { id: 'u04', name: 'Katherine Johnson' },
    ],
    dueDate: '2026-07-10',
    startDate: '2026-03-15',
    description: 'Complete UX overhaul of ShopNova\'s e-commerce platform, including checkout flow and mobile responsiveness.',
    budget: 120000,
    tags: ['UX/UI', 'Figma', 'Next.js'],
  },
  {
    id: 'p03',
    name: 'AI-Powered Analytics Engine',
    client: 'DataVault Inc.',
    status: 'in-progress',
    priority: 'high',
    progress: 44,
    team: [
      { id: 'u09', name: 'Barbara Liskov' },
      { id: 'u14', name: 'Claude Shannon' },
      { id: 'u10', name: 'Donald Knuth' },
    ],
    dueDate: '2026-10-01',
    startDate: '2026-04-20',
    description: 'Building a machine-learning analytics pipeline with real-time dashboards and predictive reporting.',
    budget: 200000,
    tags: ['Python', 'ML', 'Kafka'],
  },
  {
    id: 'p04',
    name: 'Mobile Banking App',
    client: 'FinCore Bank',
    status: 'planning',
    priority: 'critical',
    progress: 12,
    team: [
      { id: 'u07', name: 'Tim Berners-Lee' },
      { id: 'u15', name: 'Edsger Dijkstra' },
      { id: 'u16', name: 'Radia Perlman' },
      { id: 'u19', name: 'Ken Thompson' },
    ],
    dueDate: '2026-12-31',
    startDate: '2026-06-15',
    description: 'Cross-platform mobile banking application with biometric login, transfers, and real-time notifications.',
    budget: 350000,
    tags: ['React Native', 'Node.js', 'Security'],
  },
  {
    id: 'p05',
    name: 'Brand Identity Refresh',
    client: 'Lumina Creative',
    status: 'completed',
    priority: 'medium',
    progress: 100,
    team: [
      { id: 'u11', name: 'Sofia Kovalevskaya' },
      { id: 'u20', name: 'Frances Allen' },
    ],
    dueDate: '2026-06-01',
    startDate: '2026-03-01',
    description: 'Full brand identity refresh including logo design, style guide, typography system, and color palette.',
    budget: 32000,
    tags: ['Branding', 'Figma', 'Illustrator'],
  },
  {
    id: 'p06',
    name: 'Cloud Migration',
    client: 'RetailGroup Corp.',
    status: 'in-progress',
    priority: 'high',
    progress: 57,
    team: [
      { id: 'u03', name: 'Alan Turing' },
      { id: 'u08', name: 'Dennis Ritchie' },
      { id: 'u22', name: 'Bjarne Stroustrup' },
    ],
    dueDate: '2026-09-30',
    startDate: '2026-05-10',
    description: 'Migrating RetailGroup\'s on-premise infrastructure to AWS, including database replication and CI/CD pipelines.',
    budget: 180000,
    tags: ['AWS', 'DevOps', 'Terraform'],
  },
  {
    id: 'p07',
    name: 'HR Management System',
    client: 'PeopleFirst HR',
    status: 'planning',
    priority: 'medium',
    progress: 8,
    team: [
      { id: 'u06', name: 'Margaret Hamilton' },
      { id: 'u24', name: 'Anita Borg' },
      { id: 'u23', name: 'Leslie Lamport' },
    ],
    dueDate: '2026-11-15',
    startDate: '2026-07-01',
    description: 'Full-featured HR platform with onboarding flows, performance reviews, payroll integration, and reporting.',
    budget: 95000,
    tags: ['React', 'PostgreSQL', 'PDF'],
  },
  {
    id: 'p08',
    name: 'Real Estate Listing Portal',
    client: 'PropStar Realty',
    status: 'on-hold',
    priority: 'low',
    progress: 35,
    team: [
      { id: 'u13', name: 'Hedy Lamarr' },
      { id: 'u17', name: 'Vint Cerf' },
    ],
    dueDate: '2026-08-31',
    startDate: '2026-04-01',
    description: 'Property listing portal with map integration, filtering, virtual tours, and agent contact management.',
    budget: 65000,
    tags: ['Next.js', 'Maps API', 'Media'],
  },
  {
    id: 'p09',
    name: 'Cybersecurity Audit Platform',
    client: 'SecureNet Systems',
    status: 'in-progress',
    priority: 'critical',
    progress: 72,
    team: [
      { id: 'u16', name: 'Radia Perlman' },
      { id: 'u18', name: 'Shafi Goldwasser' },
      { id: 'u05', name: 'Linus Torvalds' },
    ],
    dueDate: '2026-07-31',
    startDate: '2026-03-01',
    description: 'Internal audit tool to scan, score, and remediate security vulnerabilities across enterprise environments.',
    budget: 260000,
    tags: ['Python', 'Vulnerability', 'Reports'],
  },
  {
    id: 'p10',
    name: 'Learning Management System',
    client: 'EduBridge Academy',
    status: 'review',
    priority: 'high',
    progress: 85,
    team: [
      { id: 'u12', name: 'John McCarthy' },
      { id: 'u04', name: 'Katherine Johnson' },
      { id: 'u21', name: 'Adele Goldberg' },
      { id: 'u20', name: 'Frances Allen' },
    ],
    dueDate: '2026-07-20',
    startDate: '2026-02-10',
    description: 'A comprehensive LMS with course creation tools, live sessions, assessments, progress tracking, and certificates.',
    budget: 140000,
    tags: ['Video', 'React', 'WebRTC'],
  },
  {
    id: 'p11',
    name: 'Supply Chain Dashboard',
    client: 'LogiTrack Global',
    status: 'completed',
    priority: 'medium',
    progress: 100,
    team: [
      { id: 'u09', name: 'Barbara Liskov' },
      { id: 'u10', name: 'Donald Knuth' },
    ],
    dueDate: '2026-05-31',
    startDate: '2026-01-15',
    description: 'Real-time supply chain tracking dashboard with IoT data feeds, inventory alerts, and delivery ETA predictions.',
    budget: 88000,
    tags: ['IoT', 'Charts', 'Node.js'],
  },
  {
    id: 'p12',
    name: 'Customer Support Chatbot',
    client: 'HelpdeskPro',
    status: 'planning',
    priority: 'medium',
    progress: 5,
    team: [
      { id: 'u02', name: 'Grace Hopper' },
      { id: 'u14', name: 'Claude Shannon' },
    ],
    dueDate: '2026-10-15',
    startDate: '2026-07-15',
    description: 'AI-driven customer support chatbot with intent recognition, ticket escalation, and CRM integration.',
    budget: 72000,
    tags: ['NLP', 'Python', 'OpenAI'],
  },
  {
    id: 'p13',
    name: 'Inventory Management System',
    client: 'WarehouseMax',
    status: 'on-hold',
    priority: 'low',
    progress: 22,
    team: [
      { id: 'u03', name: 'Alan Turing' },
      { id: 'u23', name: 'Leslie Lamport' },
      { id: 'u08', name: 'Dennis Ritchie' },
    ],
    dueDate: '2026-09-01',
    startDate: '2026-04-01',
    description: 'Barcode scanning inventory system with stock alerts, supplier management, and purchase order automation.',
    budget: 55000,
    tags: ['Barcode', 'PostgreSQL', 'React'],
  },
  {
    id: 'p14',
    name: 'Social Media Campaign Manager',
    client: 'BuzzMedia Agency',
    status: 'in-progress',
    priority: 'medium',
    progress: 50,
    team: [
      { id: 'u11', name: 'Sofia Kovalevskaya' },
      { id: 'u13', name: 'Hedy Lamarr' },
      { id: 'u17', name: 'Vint Cerf' },
    ],
    dueDate: '2026-08-10',
    startDate: '2026-05-20',
    description: 'Scheduling, analytics, and reporting tool for managing multi-platform social media campaigns.',
    budget: 42000,
    tags: ['Social', 'Analytics', 'Scheduler'],
  },
  {
    id: 'p15',
    name: 'Healthcare Patient Portal',
    client: 'MedCore Clinics',
    status: 'review',
    priority: 'critical',
    progress: 78,
    team: [
      { id: 'u01', name: 'Ada Lovelace' },
      { id: 'u07', name: 'Tim Berners-Lee' },
      { id: 'u19', name: 'Ken Thompson' },
      { id: 'u18', name: 'Shafi Goldwasser' },
    ],
    dueDate: '2026-07-25',
    startDate: '2026-01-10',
    description: 'HIPAA-compliant patient portal with appointment booking, medical records, telemedicine, and billing.',
    budget: 310000,
    tags: ['HIPAA', 'React', 'HL7'],
  },
]
