import type { TeamMember, Department } from './types'

export const DEPARTMENTS: Department[] = [
  'Engineering',
  'Design',
  'Product',
  'Marketing',
  'Sales',
  'Support',
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm01',
    name: 'Ada Lovelace',
    title: 'Lead Software Engineer',
    department: 'Engineering',
    email: 'ada@worknova.io',
    phone: '+1 (415) 555-0101',
    currentProject: 'WorkNova Admin Dashboard',
    workload: 85,
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    availability: 'online',
    joinedDate: '2023-01-15',
    bio: 'Passionate full-stack engineer with 10+ years of experience building scalable web applications. Loves clean architecture and mentoring junior developers.',
    location: 'San Francisco, CA',
  },
  {
    id: 'tm02',
    name: 'Grace Hopper',
    title: 'Engineering Manager',
    department: 'Engineering',
    email: 'grace@worknova.io',
    phone: '+1 (415) 555-0102',
    currentProject: 'WorkNova Admin Dashboard',
    workload: 72,
    skills: ['Team Leadership', 'Agile', 'Go', 'Architecture'],
    availability: 'online',
    joinedDate: '2022-08-01',
    bio: 'Engineering leader with a passion for building high-performing teams and delivering complex software systems on time.',
    location: 'New York, NY',
  },
  {
    id: 'tm03',
    name: 'Alan Turing',
    title: 'DevOps Engineer',
    department: 'Engineering',
    email: 'alan@worknova.io',
    phone: '+1 (312) 555-0103',
    currentProject: 'Cloud Migration',
    workload: 90,
    skills: ['Terraform', 'AWS', 'Kubernetes', 'CI/CD', 'Docker'],
    availability: 'offline',
    joinedDate: '2023-03-20',
    bio: 'Cloud infrastructure specialist focused on automating deployments and keeping production systems reliable and fast.',
    location: 'Chicago, IL',
  },
  {
    id: 'tm04',
    name: 'Katherine Johnson',
    title: 'Senior Data Analyst',
    department: 'Product',
    email: 'katherine@worknova.io',
    phone: '+1 (650) 555-0104',
    currentProject: 'AI-Powered Analytics Engine',
    workload: 65,
    skills: ['Python', 'SQL', 'Tableau', 'Machine Learning', 'Statistics'],
    availability: 'online',
    joinedDate: '2022-11-07',
    bio: 'Data analyst who turns complex datasets into actionable insights. Specializes in predictive modeling and business intelligence dashboards.',
    location: 'Palo Alto, CA',
  },
  {
    id: 'tm05',
    name: 'Linus Torvalds',
    title: 'Backend Engineer',
    department: 'Engineering',
    email: 'linus@worknova.io',
    phone: '+1 (503) 555-0105',
    currentProject: 'Cloud Migration',
    workload: 55,
    skills: ['C++', 'Rust', 'Linux', 'Networking', 'PostgreSQL'],
    availability: 'offline',
    joinedDate: '2023-06-12',
    bio: 'Low-level systems engineer with deep expertise in Linux internals and high-performance backend services.',
    location: 'Portland, OR',
  },
  {
    id: 'tm06',
    name: 'Margaret Hamilton',
    title: 'Product Manager',
    department: 'Product',
    email: 'margaret@worknova.io',
    phone: '+1 (617) 555-0106',
    currentProject: 'Healthcare Patient Portal',
    workload: 78,
    skills: ['Product Strategy', 'Roadmapping', 'Jira', 'OKRs', 'User Research'],
    availability: 'online',
    joinedDate: '2022-04-18',
    bio: 'Senior PM who bridges the gap between technical teams and business stakeholders. Expert in zero-to-one product development.',
    location: 'Boston, MA',
  },
  {
    id: 'tm07',
    name: 'Tim Berners-Lee',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    email: 'tim@worknova.io',
    phone: '+1 (206) 555-0107',
    currentProject: 'Learning Management System',
    workload: 80,
    skills: ['React', 'Web APIs', 'Accessibility', 'Performance', 'CSS'],
    availability: 'online',
    joinedDate: '2021-09-01',
    bio: 'Frontend engineer obsessed with web standards, accessibility, and pixel-perfect UI implementation.',
    location: 'Seattle, WA',
  },
  {
    id: 'tm08',
    name: 'Dennis Ritchie',
    title: 'Backend Engineer',
    department: 'Engineering',
    email: 'dennis@worknova.io',
    phone: '+1 (212) 555-0108',
    currentProject: 'Cybersecurity Audit Platform',
    workload: 40,
    skills: ['C', 'Systems Programming', 'UNIX', 'Security', 'APIs'],
    availability: 'offline',
    joinedDate: '2023-02-28',
    bio: 'Systems programmer with a strong foundation in low-level computing. Focuses on security-first API design.',
    location: 'New York, NY',
  },
  {
    id: 'tm09',
    name: 'Barbara Liskov',
    title: 'Data Scientist',
    department: 'Product',
    email: 'barbara@worknova.io',
    phone: '+1 (617) 555-0109',
    currentProject: 'AI-Powered Analytics Engine',
    workload: 70,
    skills: ['Python', 'PyTorch', 'MLOps', 'Data Pipelines', 'Statistics'],
    availability: 'online',
    joinedDate: '2022-07-14',
    bio: 'Data scientist specializing in machine learning model training and deployment at scale. Loves turning research into production.',
    location: 'Cambridge, MA',
  },
  {
    id: 'tm10',
    name: 'Donald Knuth',
    title: 'Algorithm Engineer',
    department: 'Engineering',
    email: 'donald@worknova.io',
    phone: '+1 (650) 555-0110',
    currentProject: 'Learning Management System',
    workload: 60,
    skills: ['Algorithms', 'C++', 'Java', 'Optimization', 'Complexity Analysis'],
    availability: 'online',
    joinedDate: '2021-12-05',
    bio: 'Computer scientist focused on algorithmic efficiency and correctness. Advocates for literate programming and clean code.',
    location: 'Stanford, CA',
  },
  {
    id: 'tm11',
    name: 'Sofia Kovalevskaya',
    title: 'UI/UX Designer',
    department: 'Design',
    email: 'sofia@worknova.io',
    phone: '+1 (310) 555-0111',
    currentProject: 'E-Commerce Redesign',
    workload: 75,
    skills: ['Figma', 'UX Research', 'Design Systems', 'Prototyping', 'Illustrator'],
    availability: 'online',
    joinedDate: '2022-05-23',
    bio: 'Senior designer crafting beautiful, user-centered digital experiences. Led the design system for three enterprise SaaS products.',
    location: 'Los Angeles, CA',
  },
  {
    id: 'tm12',
    name: 'John McCarthy',
    title: 'Engineering Manager',
    department: 'Engineering',
    email: 'john@worknova.io',
    phone: '+1 (408) 555-0112',
    currentProject: 'Mobile Banking App',
    workload: 68,
    skills: ['Team Leadership', 'Lisp', 'AI/ML', 'System Design', 'Mentoring'],
    availability: 'offline',
    joinedDate: '2021-06-01',
    bio: 'Engineering manager with a background in AI research. Passionate about building autonomous systems and great engineering culture.',
    location: 'San Jose, CA',
  },
  {
    id: 'tm13',
    name: 'Hedy Lamarr',
    title: 'Product Designer',
    department: 'Design',
    email: 'hedy@worknova.io',
    phone: '+1 (305) 555-0113',
    currentProject: 'E-Commerce Redesign',
    workload: 82,
    skills: ['Figma', 'Motion Design', 'After Effects', 'Branding', 'Typography'],
    availability: 'online',
    joinedDate: '2023-01-09',
    bio: 'Creative designer with a passion for motion and interaction design. Brings products to life through thoughtful visual storytelling.',
    location: 'Miami, FL',
  },
  {
    id: 'tm14',
    name: 'Claude Shannon',
    title: 'Marketing Analyst',
    department: 'Marketing',
    email: 'claude@worknova.io',
    phone: '+1 (617) 555-0114',
    currentProject: 'Social Media Campaign Manager',
    workload: 50,
    skills: ['SEO', 'Google Analytics', 'A/B Testing', 'Content Strategy', 'SQL'],
    availability: 'offline',
    joinedDate: '2023-04-17',
    bio: 'Data-driven marketing analyst who combines statistical thinking with creative campaign strategy to drive measurable growth.',
    location: 'Boston, MA',
  },
  {
    id: 'tm15',
    name: 'Edsger Dijkstra',
    title: 'Senior Backend Engineer',
    department: 'Engineering',
    email: 'edsger@worknova.io',
    phone: '+1 (512) 555-0115',
    currentProject: 'Cybersecurity Audit Platform',
    workload: 88,
    skills: ['Python', 'Algorithms', 'Distributed Systems', 'Go', 'Security'],
    availability: 'online',
    joinedDate: '2022-02-14',
    bio: 'Backend engineer focused on writing correct, elegant software. Passionate about formal methods and eliminating classes of bugs.',
    location: 'Austin, TX',
  },
  {
    id: 'tm16',
    name: 'Radia Perlman',
    title: 'Network Security Engineer',
    department: 'Engineering',
    email: 'radia@worknova.io',
    phone: '+1 (617) 555-0116',
    currentProject: 'Mobile Banking App',
    workload: 76,
    skills: ['Network Protocols', 'Security', 'Python', 'Cryptography', 'OSPF'],
    availability: 'online',
    joinedDate: '2022-09-19',
    bio: 'Network engineer with deep expertise in routing protocols and security architecture. Designed resilient systems for Fortune 500 clients.',
    location: 'Cambridge, MA',
  },
  {
    id: 'tm17',
    name: 'Vint Cerf',
    title: 'Sales Director',
    department: 'Sales',
    email: 'vint@worknova.io',
    phone: '+1 (202) 555-0117',
    currentProject: 'Real Estate Listing Portal',
    workload: 62,
    skills: ['Enterprise Sales', 'CRM', 'Salesforce', 'Negotiation', 'Partnerships'],
    availability: 'online',
    joinedDate: '2021-03-08',
    bio: 'Experienced sales leader who has closed multi-million dollar enterprise deals. Specializes in long-cycle B2B SaaS sales.',
    location: 'Washington, DC',
  },
  {
    id: 'tm18',
    name: 'Shafi Goldwasser',
    title: 'Security Researcher',
    department: 'Engineering',
    email: 'shafi@worknova.io',
    phone: '+1 (617) 555-0118',
    currentProject: 'Cybersecurity Audit Platform',
    workload: 45,
    skills: ['Cryptography', 'Zero-Knowledge Proofs', 'Python', 'Research', 'Formal Methods'],
    availability: 'offline',
    joinedDate: '2023-05-30',
    bio: 'Cryptography researcher with a focus on zero-knowledge proof systems and provable security. Bridges academic research and applied engineering.',
    location: 'Cambridge, MA',
  },
  {
    id: 'tm19',
    name: 'Ken Thompson',
    title: 'Platform Engineer',
    department: 'Engineering',
    email: 'ken@worknova.io',
    phone: '+1 (415) 555-0119',
    currentProject: 'Healthcare Patient Portal',
    workload: 73,
    skills: ['Go', 'UNIX', 'Compilers', 'Bash', 'Infrastructure'],
    availability: 'online',
    joinedDate: '2021-11-22',
    bio: 'Platform engineer who keeps the foundations solid. Specializes in developer tooling, build systems, and internal platforms.',
    location: 'San Francisco, CA',
  },
  {
    id: 'tm20',
    name: 'Frances Allen',
    title: 'Brand Designer',
    department: 'Design',
    email: 'frances@worknova.io',
    phone: '+1 (212) 555-0120',
    currentProject: 'Brand Identity Refresh',
    workload: 58,
    skills: ['Branding', 'Illustrator', 'InDesign', 'Typography', 'Print Design'],
    availability: 'online',
    joinedDate: '2023-07-04',
    bio: 'Brand designer with a sharp eye for visual identity and a love for timeless, purposeful design. Built brand systems for startups and enterprises alike.',
    location: 'New York, NY',
  },
  {
    id: 'tm21',
    name: 'Adele Goldberg',
    title: 'Senior UX Designer',
    department: 'Design',
    email: 'adele@worknova.io',
    phone: '+1 (650) 555-0121',
    currentProject: 'Learning Management System',
    workload: 66,
    skills: ['UX Research', 'Figma', 'User Testing', 'Information Architecture', 'Wireframing'],
    availability: 'online',
    joinedDate: '2022-01-10',
    bio: 'UX designer who puts users first. Runs rapid research cycles and translates insights into intuitive product flows.',
    location: 'Palo Alto, CA',
  },
  {
    id: 'tm22',
    name: 'Bjarne Stroustrup',
    title: 'Systems Engineer',
    department: 'Engineering',
    email: 'bjarne@worknova.io',
    phone: '+1 (713) 555-0122',
    currentProject: 'Cloud Migration',
    workload: 35,
    skills: ['C++', 'Systems Design', 'Memory Management', 'Performance', 'Compilers'],
    availability: 'offline',
    joinedDate: '2022-10-03',
    bio: 'Systems engineer with deep expertise in performance-critical applications. Advocates for zero-overhead abstractions and measurable results.',
    location: 'Houston, TX',
  },
  {
    id: 'tm23',
    name: 'Leslie Lamport',
    title: 'Customer Support Lead',
    department: 'Support',
    email: 'leslie@worknova.io',
    phone: '+1 (425) 555-0123',
    currentProject: 'HR Management System',
    workload: 48,
    skills: ['Zendesk', 'Technical Writing', 'SLA Management', 'Training', 'Escalation'],
    availability: 'online',
    joinedDate: '2022-03-15',
    bio: 'Support leader who ensures every customer interaction is a positive one. Reduced ticket resolution time by 40% through systematic process improvements.',
    location: 'Redmond, WA',
  },
  {
    id: 'tm24',
    name: 'Anita Borg',
    title: 'Support Manager',
    department: 'Support',
    email: 'anita@worknova.io',
    phone: '+1 (408) 555-0124',
    currentProject: 'HR Management System',
    workload: 54,
    skills: ['Team Management', 'Intercom', 'CSAT Optimization', 'Documentation', 'Onboarding'],
    availability: 'online',
    joinedDate: '2021-07-26',
    bio: 'Support manager passionate about inclusive teams and exceptional customer experiences. Advocates for support-driven development.',
    location: 'San Jose, CA',
  },
]
